_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.99432539939879
  - 40.702947991016224
  - 17
description: 'mapzen discovery '
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1391656653976
name: color testing v3
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - landbuildings.mss
  - water.mss
template: ''
