_prefs: 
  baselayer: ''
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -94.69051837921143
  - 40.716330384777606
  - 15
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1396451282564
name: Stamen Map
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - style2.mss
  - water.mss
  - roads.mss
  - labels.mss
  - landbuildings.mss
template: ''
